name: Tests

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    all-tests:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest]
                node: [21.x]

        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}

            - name: Install node modules
              run: npm install --include=dev

            - name: Lint project
              run: npx prettier --check .

            - name: Assert types
              run: |
                  npx tsc
                  npx eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0
